package com.mira.core.service;

import com.mira.core.MiraCorePlugin;
import org.bukkit.Bukkit;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.plugin.Plugin;
import org.bukkit.plugin.java.JavaPlugin;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;

public final class CoreEssentialsPresentationService {
    private final MiraCorePlugin plugin;
    private Path managedFile;
    private Path deployedFile;
    private String status = "Not synchronized";
    private int managedMessages;

    public CoreEssentialsPresentationService(MiraCorePlugin plugin) {
        this.plugin = plugin;
    }

    public boolean enabled() {
        return plugin.getConfig().getBoolean("integrations.essentials.enabled", true);
    }

    public String status() {
        return status;
    }

    public int managedMessages() {
        return managedMessages;
    }

    public Path managedFile() {
        return managedFile;
    }

    public boolean sync(boolean reloadEssentials) {
        if (!enabled()) {
            status = "Disabled in MiraCore config";
            return false;
        }

        Plugin essentials = Bukkit.getPluginManager().getPlugin("Essentials");
        if (essentials == null || !essentials.isEnabled()) {
            status = "EssentialsX is not installed/enabled";
            return false;
        }

        String locale = cleanLocale(plugin.getConfig().getString("integrations.essentials.locale", "en"));
        managedFile = plugin.getDataFolder().toPath().resolve("essentials-messages_" + locale + ".properties");
        deployedFile = essentials.getDataFolder().toPath().resolve("messages").resolve("messages_" + locale + ".properties");

        try {
            Properties defaults = loadEssentialsDefaults(essentials);
            if (defaults.isEmpty()) {
                status = "Could not read EssentialsX messages.properties";
                plugin.getLogger().warning(status);
                return false;
            }

            Properties managed = new Properties();
            if (Files.isRegularFile(managedFile)) {
                try (BufferedReader reader = Files.newBufferedReader(managedFile, StandardCharsets.UTF_8)) {
                    managed.load(reader);
                }
            }

            boolean managedChanged = false;
            for (String key : defaults.stringPropertyNames()) {
                String rawDefault = defaults.getProperty(key, "");
                String nextSeed = seedValue(key, rawDefault);

                if (!managed.containsKey(key)) {
                    managed.setProperty(key, nextSeed);
                    managedChanged = true;
                    continue;
                }

                // Upgrade only values that still exactly match MiraCore's old generated defaults.
                // Anything manually edited by the server owner is preserved.
                String current = managed.getProperty(key, "");
                String legacySeed = legacySeedValue(key, rawDefault);
                String brokenPrefixedSeed = brokenPrefixedSeedValue(key, rawDefault);
                if ((current.equals(legacySeed) || current.equals(brokenPrefixedSeed)) && !current.equals(nextSeed)) {
                    managed.setProperty(key, nextSeed);
                    managedChanged = true;
                }
            }

            Files.createDirectories(plugin.getDataFolder().toPath());
            if (!Files.exists(managedFile) || managedChanged) {
                Files.writeString(managedFile, serialize(managed,
                        "MiraCore managed EssentialsX messages. Edit this file, then run /miracore essentials sync."),
                        StandardCharsets.UTF_8);
            }

            String deployed = serialize(managed,
                    "Generated by MiraCore. Edit plugins/MiraCore/" + managedFile.getFileName() + " instead.");
            Files.createDirectories(deployedFile.getParent());

            boolean deployedChanged = !Files.isRegularFile(deployedFile)
                    || !Files.readString(deployedFile, StandardCharsets.UTF_8).equals(deployed);
            if (deployedChanged) Files.writeString(deployedFile, deployed, StandardCharsets.UTF_8);

            boolean configChanged = enforceEssentialsLocale(essentials, locale);
            managedMessages = managed.size();
            status = "Managing " + managedMessages + " EssentialsX messages for locale " + locale;

            if (reloadEssentials && (deployedChanged || configChanged)) {
                Bukkit.getScheduler().runTask(plugin, () ->
                        Bukkit.dispatchCommand(Bukkit.getConsoleSender(), "essentials:essentials reload"));
            }
            return true;
        } catch (Exception exception) {
            status = "Sync failed: " + exception.getClass().getSimpleName() + ": " + exception.getMessage();
            plugin.getLogger().warning("Essentials presentation sync failed: " + exception);
            return false;
        }
    }

    private Properties loadEssentialsDefaults(Plugin essentials) throws IOException {
        Properties properties = new Properties();
        InputStream input = essentials.getResource("messages.properties");
        if (input == null) return properties;
        try (InputStream stream = input;
             InputStreamReader reader = new InputStreamReader(stream, StandardCharsets.UTF_8)) {
            properties.load(reader);
        }
        return properties;
    }

    private boolean enforceEssentialsLocale(Plugin essentials, String locale) throws IOException {
        if (!plugin.getConfig().getBoolean("integrations.essentials.enforce-locale", true)) return false;

        Path config = essentials.getDataFolder().toPath().resolve("config.yml");
        if (!Files.isRegularFile(config)) return false;

        String original = Files.readString(config, StandardCharsets.UTF_8);
        String updated = replaceYamlScalar(original, "locale", locale);
        updated = replaceYamlScalar(updated, "per-player-locale", "false");

        if (updated.equals(original)) return false;
        Files.writeString(config, updated, StandardCharsets.UTF_8);
        return true;
    }

    private String replaceYamlScalar(String source, String key, String value) {
        String[] lines = source.split("\\R", -1);
        boolean found = false;
        for (int i = 0; i < lines.length; i++) {
            String trimmed = lines[i].trim();
            String uncommented = trimmed.startsWith("#") ? trimmed.substring(1).trim() : trimmed;
            if (!uncommented.startsWith(key + ":")) continue;
            String indent = lines[i].substring(0, lines[i].indexOf(trimmed));
            lines[i] = indent + key + ": " + value;
            found = true;
            break;
        }
        if (!found) {
            return source + (source.endsWith("\n") ? "" : "\n") + key + ": " + value + "\n";
        }
        return String.join(System.lineSeparator(), lines);
    }

    private String seedValue(String key, String value) {
        String simplified = simplify(key, value);
        return styleAndPrefix(key, simplified);
    }

    private String legacySeedValue(String key, String value) {
        return styleAndPrefix(key, value);
    }

    private String brokenPrefixedSeedValue(String key, String value) {
        String styled = simplify(key, value)
                .replace("<primary>", plugin.getConfig().getString("integrations.essentials.style.primary", "<gray>"))
                .replace("<secondary>", plugin.getConfig().getString("integrations.essentials.style.secondary", "<light_purple>"));

        if (!oldShouldPrefix(key, styled)) return styled;
        String prefix = plugin.getConfig().getString("integrations.essentials.style.prefix",
                "<dark_purple><bold>Mira</bold> <dark_gray>» <reset>");
        return (prefix == null ? "" : prefix) + styled;
    }

    private boolean oldShouldPrefix(String key, String value) {
        if (value == null || value.isBlank()) return false;
        String lower = key.toLowerCase(Locale.ROOT);
        if (lower.contains("commandusage") || lower.contains("commanddescription")) return false;
        if (lower.endsWith("format") || lower.contains("formatnew")) return false;

        List<String> excluded = plugin.getConfig().getStringList("integrations.essentials.style.no-prefix-keys");
        for (String raw : excluded) {
            if (key.equalsIgnoreCase(raw)) return false;
        }
        return true;
    }

    private String styleAndPrefix(String key, String value) {
        String styled = value;
        styled = styled.replace("<primary>", plugin.getConfig().getString(
                "integrations.essentials.style.primary", "<gray>"));
        styled = styled.replace("<secondary>", plugin.getConfig().getString(
                "integrations.essentials.style.secondary", "<light_purple>"));

        if (!plugin.getConfig().getBoolean("integrations.essentials.style.apply-prefix", false)) return styled;
        if (!shouldPrefix(key, styled)) return styled;

        // Essentials translation values are frequently nested into {0}/{1} placeholders.
        // Prefix only explicit standalone message keys. Prefixing atomic tokens such as
        // "survival", "enabled", "flying", etc. corrupts parent messages like gameMode.
        List<String> allowed = plugin.getConfig().getStringList("integrations.essentials.style.prefix-keys");
        if (allowed.stream().noneMatch(raw -> raw.equalsIgnoreCase(key))) return styled;

        String prefix = plugin.getConfig().getString("integrations.essentials.style.prefix",
                "<dark_purple><bold>Mira</bold> <dark_gray>» <reset>");
        return (prefix == null ? "" : prefix) + styled;
    }

    private String simplify(String key, String value) {
        if (!plugin.getConfig().getBoolean("integrations.essentials.simplify.enabled", true)) return value;

        return switch (key) {
            // /help and command-help output: compact and readable.
            case "commandHelpLine1" -> "<secondary>/{0}";
            case "commandHelpLine2" -> "<gray>{0}";
            case "commandHelpLine3" -> "<gray>Usage:";
            case "commandHelpLine4" -> "<gray>Aliases: <white>{0}";
            case "commandHelpLineUsage" -> "<secondary>{0}";
            case "helpFrom" -> "<gray>Commands from <secondary>{0}<gray>:";
            case "helpLine" -> "<secondary>/{0} <dark_gray>- <gray>{1}";
            case "helpMatching" -> "<gray>Matches for <secondary>{0}<gray>:";
            case "helpPlugin" -> "<secondary>{0} <dark_gray>- <gray>/help {1}";
            case "helpConsole" -> "<gray>Use <secondary>?<gray> in console.";

            // Common command failures should be one line, not Essentials prose.
            case "commandCooldown" -> "<red>Wait <white>{0}<red> before using that again.";
            case "cooldownWithMessage" -> "<red>Cooldown: <white>{0}";
            case "commandDisabled" -> "<red>That command is disabled.";
            case "commandNotLoaded" -> "<red>That command is unavailable.";
            case "consoleCannotUseCommand" -> "<red>Players only.";
            case "errorCallingCommand" -> "<red>Could not run /{0}.";
            case "errorWithMessage" -> "<red>{0}";
            case "commandFailed" -> "<red>Command failed: <white>{0}";
            case "commandHelpFailedForPlugin" -> "<red>Help unavailable for {0}.";
            case "destinationNotSet" -> "<red>No destination set.";
            case "foreverAlone" -> "<red>No one to reply to.";

            // Common confirmations.
            case "backUsageMsg" -> "<gray>Returning...";
            case "dontMoveMessage" -> "<gray>Teleporting in <secondary>{0}<gray>. Don't move.";
            case "backAfterDeath" -> "<gray>Use <secondary>/back<gray> to return.";
            case "balance" -> "<gray>Balance: <secondary>{0}";
            case "balanceOther" -> "<gray>{0}: <secondary>{1}";
            case "gameMode" -> "<gray>Gamemode: <secondary>{0}<gray> for <secondary>{1}<gray>.";
            case "gameModeInvalid" -> "<red>Choose a valid player/gamemode.";
            case "flyMode" -> "<gray>Flight <secondary>{0}<gray> for <secondary>{1}<gray>.";
            case "msgEnabled" -> "<gray>Messages enabled.";
            case "msgDisabled" -> "<gray>Messages disabled.";
            case "deleteHome" -> "<gray>Removed home <secondary>{0}<gray>.";
            case "deleteWarp" -> "<gray>Removed warp <secondary>{0}<gray>.";
            case "deleteKit" -> "<gray>Removed kit <secondary>{0}<gray>.";
            case "bedSet" -> "<gray>Bed spawn set.";
            case "backupStarted" -> "<gray>Backup started.";
            case "backupFinished" -> "<gray>Backup finished.";
            case "essentialsReload" -> "<gray>Essentials reloaded.";

            default -> simplifyDescription(key, value);
        };
    }

    private String simplifyDescription(String key, String value) {
        // Per-usage descriptions are redundant in help output. Keep them compact.
        if (key.matches(".*CommandUsage\\d+Description")) {
            String compact = value == null ? "" : value.trim();
            if (compact.endsWith(".")) compact = compact.substring(0, compact.length() - 1);
            compact = compact
                    .replace("the specified player", "player")
                    .replace("the target player", "player")
                    .replace("specified player", "player")
                    .replace("if specified", "")
                    .replace("with an optional reason", "")
                    .replace("with the given name", "")
                    .replaceAll("\\s{2,}", " ")
                    .trim();
            return "<gray>" + compact;
        }

        if (key.endsWith("CommandDescription")) {
            String compact = value == null ? "" : value.trim();
            if (compact.endsWith(".")) compact = compact.substring(0, compact.length() - 1);
            return compact;
        }

        return value;
    }

    private boolean shouldPrefix(String key, String value) {
        if (value == null || value.isBlank()) return false;

        String lower = key.toLowerCase(Locale.ROOT);
        if (lower.contains("commandusage") || lower.contains("commanddescription")) return false;
        if (lower.endsWith("format") || lower.contains("formatnew")) return false;

        // Single-token translations are commonly injected into other translated messages.
        // Never decorate them as standalone chat output.
        String plain = value.replaceAll("<[^>]+>", "").trim();
        if (!plain.contains(" ") && !plain.contains("\\n")) return false;

        List<String> excluded = plugin.getConfig().getStringList("integrations.essentials.style.no-prefix-keys");
        for (String raw : excluded) {
            if (key.equalsIgnoreCase(raw)) return false;
        }
        return true;
    }

    private static String cleanLocale(String raw) {
        if (raw == null || raw.isBlank()) return "en";
        String cleaned = raw.trim().replace('-', '_');
        return cleaned.matches("[A-Za-z_]+") ? cleaned : "en";
    }

    private static String serialize(Properties properties, String header) {
        StringBuilder out = new StringBuilder();
        out.append("# ").append(header).append('\n');
        TreeSet<String> keys = new TreeSet<>(properties.stringPropertyNames());
        for (String key : keys) {
            out.append(escape(key, true)).append('=')
                    .append(escape(properties.getProperty(key, ""), false)).append('\n');
        }
        return out.toString();
    }

    private static String escape(String value, boolean key) {
        StringBuilder out = new StringBuilder(value.length() + 8);
        for (int i = 0; i < value.length(); i++) {
            char c = value.charAt(i);
            switch (c) {
                case '\\' -> out.append("\\\\");
                case '\t' -> out.append("\\t");
                case '\n' -> out.append("\\n");
                case '\r' -> out.append("\\r");
                case '\f' -> out.append("\\f");
                case '=', ':' -> {
                    if (key) out.append('\\');
                    out.append(c);
                }
                case '#', '!' -> {
                    if (key || i == 0) out.append('\\');
                    out.append(c);
                }
                case ' ' -> {
                    if (i == 0) out.append('\\');
                    out.append(' ');
                }
                default -> out.append(c);
            }
        }
        return out.toString();
    }
}
